name: Compile and Upload Resume PDF
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.pdf'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:2021-05-01
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          
          
      - name: Build LaTeX
        run: |
          for project in $(ls *.tex); do
              latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf "${PWD}/${project}" -outdir=$PWD 
          done
          
      - name: Post Processing
        run: |
          mkdir build
          cp *.pdf build/
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.LATEX_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
          
